spring:
  application:
    name: user-service-java
  lifecycle:
    timeout-per-shutdown-phase: 30m

  task:
    execution:
      shutdown:
        await-termination: true
        await-termination-period: 30m

server:
  port: 5002
  http2:
    enabled: true
  servlet:
      context-path: /api/v1
  graceful-shutdown:
    enabled: true
    timeout: 10m