spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/auth
    username: root
    password: root
    pool:
      enabled: true
      initial-size: 10
      max-size: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  flyway:
    url: jdbc:mysql://localhost:3306/auth
    password: root
    user: root